#ifndef _ERRORCODE_H__
#define _ERRORCODE_H__

#define FILE_TASK_USER_CANCELED			(1000)
#define FILE_TASK_USER_STOPPED			(1001)

#define ERR_UNKNOWN						(2000)
#define ERR_PATH_INCORRECT				(2001)
#define ERR_ALLOC_FAILED				(2002)
#define ERR_EMPTY_DIRECTORY				(2003)
#define ERR_NO_MEDIA_INDEVICE           (2004)
#define ERR_ACCESS_DENIED				(2005)

#define ERR_TARGET_OFFLINE				(3000)
#define ERR_CONTRL_FILECONN_OFFLINE		(3001)
#define ERR_TARGET_FILECONN_OFFLINE		(3002)
#define ERR_DAEMON_PLUGIN_UPDATE		(3003)
#define ERR_TARGET_PLUGIN_UPDATE		(3004)
#define ERR_TARGET_INEXIST				(3005)
#define ERR_PLUGIN_INEXIST				(3006)
#define ERR_PLUGIN_UPDATE_TYPE_INMATCH	(3007)

//
// File Operation Error Code
//
#define ERR_TASK_EXISTED				(3010)
#define ERR_FILE_TASK_RUNNING			(3011)
#define ERR_FILE_TASK_STATUS_INCORRECT  (3012)
#define ERR_FILE_TASK_INEXIST			(3013)
#define ERR_FILE_TASK_SWITCHED			(3014)
#define ERR_UNKNOWN_FILE_TASK_TYPE		(3015)
#define ERR_FILE_TASK_DELETE			(3016)
#define ERR_RED_EFS_FILE				(3017)
#define ERR_FILE_TASK_CANCEL			(3018)

#define ERR_RED_FILE_OPEN				(3021)
#define ERR_WRT_FILE_OPEN				(3022)
#define ERR_RED_FILE_SEEK				(3023)
#define ERR_WRT_FILE_SEEK				(3024)
#define ERR_RED_FILE_READ				(3025)
#define ERR_WRT_FILE_WRITE				(3026)
#define ERR_RED_FILE_SIZE_CHANGED		(3027)
#define ERR_WRT_FILE_SIZE_CHANGED		(3028)
#define ERR_RED_FILE_END				(3029)

#define ERR_DEL_FILE_SHARING_VIOLATION	(3030)

//
// Plugin Operation Error Code
//
#define ERR_KJET_ACCESS_FAILED			(3999)
#define ERR_PLG_FILE_INEXIST			(4000)
#define ERR_PLG_LOAD_FAILED				(4001)
#define ERR_PLG_UNLOAD_FAILED			(4002)
#define ERR_PLG_GETVERSION_FAILED		(4005)
#define ERR_PLG_VERSION_INCORRECT		(4006)
#define	ERR_PLG_NEED_NOT_LOAD			(4007)

#endif